// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKoA8ln4XM5TuzHW5kQO03bxbarHVTM6M',
    appId: '1:855291841149:web:9fc77183264282448b3f14',
    messagingSenderId: '855291841149',
    projectId: 'peliculas-moviles3',
    authDomain: 'peliculas-moviles3.firebaseapp.com',
    storageBucket: 'peliculas-moviles3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDMUfxOA8lpQPLgkO8BxoJHcRT0cQBS2c',
    appId: '1:855291841149:android:73ae664f05f5bce78b3f14',
    messagingSenderId: '855291841149',
    projectId: 'peliculas-moviles3',
    storageBucket: 'peliculas-moviles3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKoA8ln4XM5TuzHW5kQO03bxbarHVTM6M',
    appId: '1:855291841149:web:71d991bd31096a048b3f14',
    messagingSenderId: '855291841149',
    projectId: 'peliculas-moviles3',
    authDomain: 'peliculas-moviles3.firebaseapp.com',
    storageBucket: 'peliculas-moviles3.firebasestorage.app',
  );

}